apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx-deploy
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/instance: nginx-deploy
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nginx-service
    app.kubernetes.io/name: nginx
spec:
  ports:
  - nodePort: 30331
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginx
  type: NodePort