apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: django-deploy
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
        app.kubernetes.io/name: django
        app.kubernetes.io/instance: django-deploy
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - name: django
          image: barseeek/django_app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-secret
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "curl -X PUT --data-binary @/docker-entrypoint.d/unit_config.json --unix-socket /var/run/control.unit.sock http://localhost/config"]

