apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: django
          image: barseeek/django_app
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate", "--no-input"]
          envFrom:
            - secretRef:
                name: django-secret
      restartPolicy: OnFailure